<?php
/**
 * Created by PhpStorm.
 * User: shuns
 * Date: 26/02/2018
 * Time: 11:57
 */

namespace AppBundle\Controller;


use AppBundle\Entity\Movie;
use AppBundle\Form\MovieType;
use AppBundle\Manager\MovieManager;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;

class MovieController extends Controller
{
    /**
     * @Route("/admin/addMovie", name="add_movie")
     */
    public function addMovie(Request $request,  MovieManager $movieManager)
    {
        $movie = new Movie();
        $form = $this->createForm(MovieType::class, $movie);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // $file stores the uploaded PDF file
            /** @var UploadedFile $file */
            $file = $movie->getImage();

            $fileName = $this->generateUniqueFileName().'.'.$file->guessExtension();

            // moves the file to the directory where brochures are stored
            $file->move(
                $this->getParameter('images_directory'),
                $fileName
            );

            $movie->setImage($fileName);
            $movieManager->createMovie($movie);

            // ... persist the $product variable or any other work

            return $this->redirect($this->generateUrl('list_movies'));
        }

        return $this->render('admin/new-movie.html.twig', array(
            'form' => $form->createView(),
        ));
    }

    /**
     * @return string
     */
    private function generateUniqueFileName()
    {
        // md5() reduces the similarity of the file names generated by
        // uniqid(), which is based on timestamps
        return md5(uniqid());
    }
}