<?php

namespace AppBundle\Repository;

/**
 * categoryUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryUserRepository extends \Doctrine\ORM\EntityRepository
{
}
