<?php

namespace AppBundle\Repository;

/**
 * categoryMovieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categoryMovieRepository extends \Doctrine\ORM\EntityRepository
{
}
