security:
    encoders:
        AppBundle\Entity\User: bcrypt

    providers:
        user:
            entity:
                class: AppBundle\Entity\User
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: user
            anonymous: ~
            form_login:
                login_path: sign_in
                check_path: sign_in
                default_target_path: home
            logout:
                path: sign_out
                target: sign_in

    access_control:
        - { path: ^/home, roles: ["ROLE_USER", "ROLE_ADMIN"]}
        - { path: ^/admin, roles: "ROLE_ADMIN" }